[package]
name = "pass_context"
version = "0.1.0"
authors = ["haowei <weix.hao@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fuzzlib = { path = "../fuzzlib" }
log = "0.4.13"
simple_logger = "1.11.0"
