# This is a basic workflow to help you get started with Actions

name: RUN CODE

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runs-on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-08-08
          override: true
          components: rust-src, rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build and Run test
        shell: bash
        env:
          CC_x86_64_unknown_none: clang
          AR_x86_64_unknown_none: llvm-ar
          CC_x86_64_unknown_uefi: clang
          AR_x86_64_unknown_uefi: llvm-ar
        run: |
          ./sh_script/build.sh -c
          ./sh_script/build.sh -r
