# This is a basic workflow to help you get started with Actions

name: RUN CODE

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows_build-dont_run_fuzz:
    # The type of runner that the job will run on
#     runs-on: ubuntu-latest
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-08-08
          override: true
          components: rust-src
      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: no_std check
        env:
          CC: clang
          AR: llvm-ar
        run: |
          pushd spdmlib
          cargo build -Z build-std=core,alloc,compiler_builtins --target x86_64-unknown-uefi --release --no-default-features --features="spdm-ring"

      - name: cargo build
        run: |
          cargo build -p spdm-responder-emu &
          cargo build -p spdm-requester-emu

      - name: cargo tests
        run: cargo test

      - name: run responder and requester script
        run: |
          cargo run -p spdm-responder-emu &
          cargo run -p spdm-requester-emu
  linux_build-run_fuzz:
    # The type of runner that the job will run on
#     runs-on: ubuntu-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v2

      - name: no std check
        run: |
          rustup component add rust-src
          pushd spdmlib
          cargo build -Z build-std=core,alloc,compiler_builtins --target x86_64-unknown-uefi --release --no-default-features --features="spdm-ring"

      - name: cargo build
        run: |
          cargo build -p spdm-responder-emu -p spdm-requester-emu

      - name: Build fuzz
        run: ./sh_script/fuzz_run.sh -b

      - name: cargo tests
        run: cargo test

      - name: run responder and requester script
        run: |
          cargo run -p spdm-responder-emu &
          sleep 5
          cargo run -p spdm-requester-emu
